name: Snake Animation  

on:  
  schedule:  
    - cron: "0 0 * * *"  # Runs at midnight every day  
  push:  
    branches:  
      - main  # Change this to your default branch if needed  

jobs:  
  update-snake:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Update Snake  
        uses: Platane/snk@master  
        with:  
          github_user: 'Osama-keakaty'  # Replace with your username  
          svg_out: 'output/snake.svg'  
          html_out: 'output/snake.html'
